/* Generate TOKENS.md from the values the ten pages actually compute.
   Nothing is averaged or tidied: where pages disagree, the disagreement is
   printed with the pages that hold each value. */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../../..');
const SRC = process.env.TOKENS || 'C:/Users/Sigoff/AppData/Local/Temp/claude/c------WORK-AAN-CONTROL-PANEL/9fea96e9-7862-4244-9ba4-4dc3cf5b706e/scratchpad/tokens.json';
const OUT = path.join(ROOT, 'design-system/gen11/TOKENS.md');

const j = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const PAGES = Object.keys(j);

const all = {};
for (const p of PAGES) for (const [k, v] of Object.entries(j[p].vars)) (all[k] = all[k] || {})[p] = v;

const GROUPS = [
  ['Type', /^--(font|mono)$/],
  ['Spacing ladder', /^--s\d$/],
  ['Structural spacing', /^--(gutter|inset|inset-ctl|sheet-inset|col-gap|gap|zone-air)$/],
  ['Control heights', /^--(ctl|ctl-dense|ctl-lg|ctl-h|field-h|btn-h|row|hd-size|hd-track)/],
  ['Sticky geometry', /^--(bar-track|top|headh|stick|cmdh|hdh|bento-h|anchor-gap)/],
  ['Radius', /^--r-/],
  ['Ground and surfaces', /^--(ground|sheet|wash|well|line)/],
  ['Ink', /^--ink/],
  ['Brand', /^--brand/],
  ['Focal (dark)', /^--focal/],
  ['Semantic', /^--(ok|danger|signal|slate|violet|accent|age)/],
  ['Status tints', /^--(t-|status)/],
  ['Elevation and glass', /^--(el-|sh-|glass|edge)/],
  ['Focus', /^--focus/],
  ['Layers', /^--z-/],
  ['Motion', /^--(dur|ease)/],
  ['Layout widths', /^--(lot|dock|max|content)/],
];

const L = [];
const w = s => L.push(s);
const claimed = new Set();

w('# Gen 11 — TOKENS');
w('');
w('The values the ten shipped pages actually compute, read out of the running');
w('product rather than out of a spec. Generated by `_tools/gen-tokens.js`.');
w('');
const agree = Object.entries(all).filter(([, m]) => new Set(Object.values(m)).size === 1);
const differ = Object.entries(all).filter(([, m]) => new Set(Object.values(m)).size > 1);
w('| | |');
w('|---|---|');
w(`| distinct custom properties | **${Object.keys(all).length}** |`);
w(`| same value on every page that declares them | **${agree.length}** |`);
w(`| genuinely differ between pages | **${differ.length}** |`);
w('');
w('A token layer that agrees with itself on ' + Math.round(agree.length / Object.keys(all).length * 100) +
  '% of its surface is the reason the family');
w('reads as one product. The five disagreements below are real and are kept.');
w('');
w('---');
w('');
w('## Where the pages disagree');
w('');
w('| token | value | pages |');
w('|---|---|---|');
for (const [k, m] of differ) {
  const byVal = {};
  for (const [p, v] of Object.entries(m)) (byVal[v] = byVal[v] || []).push(p);
  const entries = Object.entries(byVal);
  entries.forEach(([v, ps], i) => {
    w(`| ${i === 0 ? '`' + k + '`' : ''} | \`${v}\` | ${ps.join(', ')} |`);
  });
}
w('');
w('`--row` is table density and is meant to differ: an inventory row carries a');
w('thumbnail, a work-queue row carries seventeen columns of text. `--dock` is the');
w('width of a contextual panel and follows what the panel holds. `--stick-total`');
w('is derived from the sticky layers a page actually has, which is why it must');
w('never be hardcoded. `--anchor-gap` and the mono fallback list are the two that');
w('could be unified and have not been.');
w('');
w('---');
w('');

for (const [title, re] of GROUPS) {
  const keys = Object.keys(all).filter(k => re.test(k) && !claimed.has(k)).sort();
  if (!keys.length) continue;
  keys.forEach(k => claimed.add(k));
  w(`## ${title}`);
  w('');
  w('| token | value | declared on |');
  w('|---|---|---|');
  for (const k of keys) {
    const m = all[k];
    const vals = [...new Set(Object.values(m))];
    const v = vals.length === 1 ? vals[0] : vals.map(x => '`' + x + '`').join(' / ');
    w(`| \`${k}\` | ${vals.length === 1 ? '`' + v + '`' : v} | ${Object.keys(m).length} of ${PAGES.length} pages |`);
  }
  w('');
}

const rest = Object.keys(all).filter(k => !claimed.has(k)).sort();
if (rest.length) {
  w('## Everything else');
  w('');
  w('| token | value | declared on |');
  w('|---|---|---|');
  for (const k of rest) {
    const m = all[k], vals = [...new Set(Object.values(m))];
    w(`| \`${k}\` | ${vals.map(x => '`' + x + '`').join(' / ')} | ${Object.keys(m).length} of ${PAGES.length} pages |`);
  }
  w('');
}

w('---');
w('');
w('## How to use them');
w('');
w('Take the tokens from `dist/aan-gen11.css`, which carries the shared layer. The');
w('page-level tokens above (`--row`, `--cols`, `--dock`) belong to the page: a new');
w('page declares its own, on the ladder, and does not borrow another page\'s value');
w('because it happens to be nearby.');
w('');
w('The ladder is `4 · 8 · 12 · 16 · 24 · 32 · 40 · 48 · 64`. A value off the ladder');
w('is a decision that has to be defensible in a comment, not a rounding error.');

fs.writeFileSync(OUT, L.join('\n'));
console.log('TOKENS.md', L.length, 'lines |', Object.keys(all).length, 'tokens,', differ.length, 'disagreements');
