// Real rows extracted from aan-design-export-2026-09-09/pages/d03-inventory-1.html (Chicago Motor Cars #277, Available lane, page 1 of 4)
window.AAN_VEHICLES = [
 {
  "id": "12441",
  "thumb": "8ccfc032-12441_main_t.jpg",
  "stock": "001253 PS",
  "year": 2005,
  "make": "Porsche",
  "model": "Carrera GT",
  "trim": "Only 953 Miles! Serviced! Full Luggage! Collector Quality!",
  "ext": "GT Silver Metallic",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set"
  ],
  "days": 23,
  "ageLabel": "23d",
  "ageBand": "green",
  "lock": null
 },
 {
  "id": "13868",
  "thumb": "277624e2-13868_main_t.jpg",
  "stock": "0P0300236 PS",
  "year": 2023,
  "make": "Ferrari",
  "model": "812 GTS",
  "trim": "Convertible Tailor Made Only 1600 Miles Final Year 1 of 1 Collector Grade",
  "ext": "Verde Zeltweg",
  "price": 1099500,
  "status": "Available",
  "flags": [],
  "days": 40,
  "ageLabel": "40d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "13663",
  "thumb": "97253f70-13663_main_t.jpg",
  "stock": "1284NEBR MS",
  "year": 1967,
  "make": "Chevrolet",
  "model": "Corvette",
  "trim": "LS3 525hp Restomod Coffman Chassis NCRS Awarded",
  "ext": "Goodwood Green",
  "price": 259500,
  "status": "Available",
  "flags": [],
  "days": 100,
  "ageLabel": "100d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "8448",
  "thumb": null,
  "stock": "18421",
  "year": 2021,
  "make": "SUNDOWNER",
  "model": "SUNLITE ARGO 40GN",
  "trim": "TRAILER",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 1917,
  "ageLabel": "5.3y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "13706",
  "thumb": "5c5f045c-13706_main_t.jpg",
  "stock": "185618 GB",
  "year": 2018,
  "make": "Porsche",
  "model": "911 GT2 RS",
  "trim": "Weissach Package Only 2k Miles Magnesium Wheels Full PPF LOADED",
  "ext": "Guards Red",
  "price": 899500,
  "status": "Available",
  "flags": [],
  "days": 84,
  "ageLabel": "84d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "10166",
  "thumb": "d91496ae-10166_main_t.jpg",
  "stock": "18837C",
  "year": 2017,
  "make": "Kia",
  "model": "Forte",
  "trim": "LX Sedan Snow White Pearl Popular Package Rearview Camera Well Equipped",
  "ext": "Snow White Pearl",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 1409,
  "ageLabel": "3.9y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "9678",
  "thumb": "f7aed7d4-9678_main_t.jpg",
  "stock": "19495",
  "year": 2016,
  "make": "Kenworth",
  "model": "W900L",
  "trim": "ICON 900 SLEEPER 44 BUILT CUMMINS ISX 550 HORSEPOWER 18 SPEED",
  "ext": "Daydream Blue",
  "price": 100800,
  "status": "Available",
  "flags": [],
  "days": 1566,
  "ageLabel": "4.3y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "10374",
  "thumb": null,
  "stock": "19953",
  "year": 1995,
  "make": "Ford",
  "model": "Mustang SVT",
  "trim": "Cobra R Coupe Only 699 Miles Collector Quality 5 Speed Manual",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 1332,
  "ageLabel": "3.6y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "13478",
  "thumb": "bda50d2c-13478_main_t.jpg",
  "stock": "1X289324 JJ",
  "year": 2018,
  "make": "Mercedes-Benz",
  "model": "G550 4X4 Squared",
  "trim": "B40-500 Brabus Amazing Combo Carbon Fiber Everywhere Sunroof Loaded",
  "ext": "Black",
  "price": 199500,
  "status": "Available",
  "flags": [],
  "days": 156,
  "ageLabel": "156d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "10640",
  "thumb": "86a2b92c-10640_main_t.jpg",
  "stock": "20171",
  "year": 2010,
  "make": "Peterbilt",
  "model": "384",
  "trim": "Single Axle",
  "ext": "White",
  "price": 42800,
  "status": "Available",
  "flags": [],
  "days": 1241,
  "ageLabel": "3.4y",
  "ageBand": "red",
  "lock": "Being edited by Ivaylo Guenkov since 09/09/2026 08:52 PM"
 },
 {
  "id": "9672",
  "thumb": null,
  "stock": "20369A",
  "year": 1993,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "Coupe 5 Speed Manual 21k Miles Collector Quality Condition Rare",
  "ext": "Electric Red Clearcoat Metallic",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 1132,
  "ageLabel": "3.1y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11155",
  "thumb": null,
  "stock": "20536",
  "year": 2010,
  "make": "Terex",
  "model": "PT100F",
  "trim": "High Flow Compact Track",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set"
  ],
  "days": 1069,
  "ageLabel": "2.9y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11287",
  "thumb": null,
  "stock": "20634",
  "year": 1995,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "R Coupe Only 744 Miles 5-Speed Manual Collector Quality Condition",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 1024,
  "ageLabel": "2.8y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11369",
  "thumb": null,
  "stock": "20710",
  "year": 2002,
  "make": "Cadillac",
  "model": "Eldorado",
  "trim": "ETC Diamond White Last Year Made Northstar Collectible 700 Miles",
  "ext": "White Diamond",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 988,
  "ageLabel": "2.7y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11460",
  "thumb": null,
  "stock": "20788",
  "year": 1996,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "Coupe Mystic Chrome Only 2200 Miles 5-Speed Manual Collector Quality",
  "ext": "Mystic Clearcoat Metallic",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 951,
  "ageLabel": "2.6y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11516",
  "thumb": "b8a46d1e-11516_main_t.jpg",
  "stock": "20828",
  "year": 1998,
  "make": "Porsche",
  "model": "911 993 Turbo",
  "trim": "XLC Coupe Painted Sport Seat Backs 6 Speed Manual Transmission 51k Miles",
  "ext": "Black",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 938,
  "ageLabel": "2.6y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "13918",
  "thumb": "4412bb96-13918_main_t.jpg",
  "stock": "20834E",
  "year": 2014,
  "make": "Dodge",
  "model": "SRT Viper",
  "trim": "GTS Prefix 9L Xtreme Laguna Interior TA 1.0 Carbon Aero 6 Vent Hood Loaded",
  "ext": "Venom Black Clear coat",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set"
  ],
  "days": 23,
  "ageLabel": "23d",
  "ageBand": "green",
  "lock": null
 },
 {
  "id": "11558",
  "thumb": null,
  "stock": "20870",
  "year": 1991,
  "make": "Mercedes-Benz",
  "model": "SL 60 AMG",
  "trim": "Convertible 1 of 50 Ever Produced",
  "ext": "Arctic White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 926,
  "ageLabel": "2.5y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11934",
  "thumb": null,
  "stock": "21221",
  "year": 1995,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "R 2k Mile SVT Certificate Full Original Belongings Included Immaculate",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 729,
  "ageLabel": "2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11945",
  "thumb": null,
  "stock": "21227",
  "year": 1993,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "Coupe 5 Speed Manual Only 42k Miles Collector Quality Condition",
  "ext": "Bright Red",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 727,
  "ageLabel": "2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11947",
  "thumb": null,
  "stock": "21229",
  "year": 2000,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "R Only 22 Original Delivery Miles Collector Quality Condition",
  "ext": "Performance Red Clearcoat",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 727,
  "ageLabel": "2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11949",
  "thumb": null,
  "stock": "21230",
  "year": 2000,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "R Coupe 5 Speed Manual Only 2k Miles Collector Quality Condition",
  "ext": "Performance Red Clearcoat",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 727,
  "ageLabel": "2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11950",
  "thumb": null,
  "stock": "21231",
  "year": 1993,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "R Coupe 5 Speed Manual Only 449 Miles Collector Quality Condition",
  "ext": "Bright Red",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 727,
  "ageLabel": "2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11953",
  "thumb": null,
  "stock": "21234",
  "year": 1995,
  "make": "Honda",
  "model": "ACTY",
  "trim": "Pick Up Truck Right Hand Drive Automatic 656cc Inline 3 Cylinder",
  "ext": "Yellow",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set"
  ],
  "days": 726,
  "ageLabel": "2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12208",
  "thumb": null,
  "stock": "21437",
  "year": 1989,
  "make": "Mercedes-Benz",
  "model": "190E",
  "trim": "2.5-16 Evolution Sedan",
  "ext": "Gray",
  "price": 259500,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 631,
  "ageLabel": "1.7y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "9953",
  "thumb": null,
  "stock": "21507",
  "year": 1995,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "R Coupe 5 Speed Manual Only 1k Miles Collector Quality Condition",
  "ext": "White",
  "price": 69500,
  "status": "Available",
  "flags": [
   "No photos uploaded"
  ],
  "days": 589,
  "ageLabel": "1.6y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12354",
  "thumb": null,
  "stock": "21562",
  "year": 1998,
  "make": "Porsche",
  "model": "911 Turbo XLC",
  "trim": "Coupe X50 Turbo 6 Speed Manual Transmission 45k Miles Clean Example",
  "ext": "Red",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 562,
  "ageLabel": "1.5y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "13744",
  "thumb": "b48d9668-13744_main_t.jpg",
  "stock": "21577B",
  "year": 1978,
  "make": "Ferrari",
  "model": "308 GTS",
  "trim": "Only 15k Miles 2 Tops! Just at Serviced Ferrari Collector Quality",
  "ext": "Silver",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 71,
  "ageLabel": "71d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "13745",
  "thumb": "80d11de6-13745_main_t.jpg",
  "stock": "21577C",
  "year": 1971,
  "make": "Lamborghini",
  "model": "Espada Series II",
  "trim": "V12 5 Speed Manual Collector Car 1 of 575 Ever Produced",
  "ext": "Silver",
  "price": 149500,
  "status": "Available",
  "flags": [],
  "days": 71,
  "ageLabel": "71d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "12395",
  "thumb": "a1414776-12395_main_t.jpg",
  "stock": "21604",
  "year": 1999,
  "make": "Mercedes-Benz",
  "model": "C43 AMG",
  "trim": "Sedan 1 of 1 Lapis Blue 69k Miles 4.3L V8 Collector Quality Rare",
  "ext": "Sonderlackierung (special-order) non-metallic Lapis Blu",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set"
  ],
  "days": 548,
  "ageLabel": "1.5y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12608",
  "thumb": null,
  "stock": "21788",
  "year": 1977,
  "make": "Jensen",
  "model": "Interceptor III",
  "trim": "",
  "ext": "Green",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 468,
  "ageLabel": "1.3y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12610",
  "thumb": "1f033fea-12610_main_t.jpg",
  "stock": "21790",
  "year": 1992,
  "make": "Jensen",
  "model": "Interceptor S4",
  "trim": "Fastback Extremely Rare British Wood Finishes Sport Seats Just Serviced",
  "ext": "Green",
  "price": 99500,
  "status": "Available",
  "flags": [],
  "days": 468,
  "ageLabel": "1.3y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12633",
  "thumb": "fc28a6e8-12633_main_t.jpg",
  "stock": "21814",
  "year": 2006,
  "make": "Ford",
  "model": "Super Duty F-750 XL",
  "trim": "",
  "ext": "White",
  "price": 48800,
  "status": "Available",
  "flags": [],
  "days": 457,
  "ageLabel": "1.3y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12654",
  "thumb": "40c6feea-12654_main_t.jpg",
  "stock": "21834",
  "year": 2016,
  "make": "Chaparral",
  "model": "243",
  "trim": "Jet Boat",
  "ext": "Black",
  "price": 42800,
  "status": "Available",
  "flags": [],
  "days": 450,
  "ageLabel": "1.2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12687",
  "thumb": "da19ce2a-12687_main_t.jpg",
  "stock": "21848",
  "year": 1993,
  "make": "Toyota",
  "model": "Supra",
  "trim": "Turbo Built and Fresh Major Service by Sound Performance",
  "ext": "Orange",
  "price": 119500,
  "status": "Available",
  "flags": [],
  "days": 441,
  "ageLabel": "1.2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12716",
  "thumb": "b2180cdc-12716_main_t.jpg",
  "stock": "21868A",
  "year": 2024,
  "make": "Mercedes-Benz",
  "model": "Sprinter",
  "trim": "3500 Ultimate Coach Executive TV Bluetooth WIFI Bathroom LOADED",
  "ext": "Jet Black",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Sale pending"
  ],
  "days": 428,
  "ageLabel": "1.2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12732",
  "thumb": null,
  "stock": "21890",
  "year": 2010,
  "make": "Sea Ray",
  "model": "300",
  "trim": "Bowrider",
  "ext": "White",
  "price": 62500,
  "status": "Available",
  "flags": [
   "No photos uploaded"
  ],
  "days": 422,
  "ageLabel": "1.2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12741",
  "thumb": null,
  "stock": "21897",
  "year": 1987,
  "make": "Lamborghini",
  "model": "LM002",
  "trim": "",
  "ext": "Black",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 421,
  "ageLabel": "1.2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12742",
  "thumb": "b59227aa-12742_main_t.jpg",
  "stock": "21898",
  "year": 1989,
  "make": "Lamborghini",
  "model": "Countach",
  "trim": "25th Anniversary Edition 1/657 Made RARE Color Combo Collector Quality",
  "ext": "Black",
  "price": 750000,
  "status": "Available",
  "flags": [],
  "days": 421,
  "ageLabel": "1.2y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "11865",
  "thumb": "f5c2cee4-11865_main_t.jpg",
  "stock": "21927",
  "year": 2018,
  "make": "Porsche",
  "model": "911 GT2 RS",
  "trim": "Weissach Magnesium Wheels Paint to Sample Volcano Grey Full PPF",
  "ext": "Paint to Sample Volcano Grey",
  "price": 899500,
  "status": "Available",
  "flags": [],
  "days": 408,
  "ageLabel": "1.1y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12844",
  "thumb": "1798d6a4-12844_main_t.jpg",
  "stock": "21974",
  "year": 2022,
  "make": "Mastercraft",
  "model": "XT24",
  "trim": "2022 Mastercraft XT 24",
  "ext": "White",
  "price": 138800,
  "status": "Available",
  "flags": [],
  "days": 378,
  "ageLabel": "1y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12884",
  "thumb": null,
  "stock": "22010",
  "year": 2025,
  "make": "Audi",
  "model": "Q5 Premium Plus 55",
  "trim": "Quattro Navigation Heated Seats 9k Miles Clean History",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 371,
  "ageLabel": "1y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12897",
  "thumb": null,
  "stock": "22022",
  "year": 2018,
  "make": "Porsche",
  "model": "911 GT2 RS",
  "trim": "Weissach Pkg PTS Gulf Blue Axle Lifter Carbon Fiber Everywhere PPF",
  "ext": "PTS - Gulf Blue",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 366,
  "ageLabel": "1y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "12900",
  "thumb": "bf54b7a2-12900_main_t.jpg",
  "stock": "22028",
  "year": 1997,
  "make": "Ford",
  "model": "Mustang Saleen S351",
  "trim": "Speedster Collector Condition 1 of ONLY 40 Made ONLY 15k Miles",
  "ext": "Crystal White Clearcoat",
  "price": 99500,
  "status": "Available",
  "flags": [],
  "days": 365,
  "ageLabel": "365d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "12903",
  "thumb": null,
  "stock": "22031",
  "year": 2025,
  "make": "Full Scale",
  "model": "Vintage Replica",
  "trim": "",
  "ext": "",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 365,
  "ageLabel": "365d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "12836",
  "thumb": "f3f27d5e-12836_main_t.jpg",
  "stock": "22078A",
  "year": 2006,
  "make": "Ford",
  "model": "GT",
  "trim": "Rare Factory No Stripe Car HRE Wheels Ford Racing Headers Tons of Upgrades",
  "ext": "Mark II Black Clearcoat",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 302,
  "ageLabel": "302d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "12342",
  "thumb": "8f93a7b2-12342_main_t.jpg",
  "stock": "22096A",
  "year": 2024,
  "make": "Porsche",
  "model": "911",
  "trim": "Targa 4S + Upgrades! Only 4k Miles! HREs! Premium Pkg! Front Lift!",
  "ext": "GT Silver Metallic",
  "price": 195500,
  "status": "Available",
  "flags": [],
  "days": 163,
  "ageLabel": "163d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "12985",
  "thumb": "9e119f28-12985_main_t.jpg",
  "stock": "22102",
  "year": 1965,
  "make": "Backdraft Shelby",
  "model": "Cobra",
  "trim": "",
  "ext": "Gray",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 335,
  "ageLabel": "335d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "12379",
  "thumb": "59f494ea-12379_main_t.jpg",
  "stock": "22112D",
  "year": 2024,
  "make": "Land Rover",
  "model": "Range Rover",
  "trim": "P530 SE Meridian Premium Sound Towing Pkg Black Contrast Roof",
  "ext": "Hakuba Silver Metallic",
  "price": 135000,
  "status": "Available",
  "flags": [],
  "days": 203,
  "ageLabel": "203d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "10710",
  "thumb": null,
  "stock": "22114A",
  "year": 2005,
  "make": "Porsche",
  "model": "Carrera GT",
  "trim": "",
  "ext": "Mexico Blue",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 323,
  "ageLabel": "323d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "11523",
  "thumb": "10073ee6-11523_main_t.jpg",
  "stock": "22127E",
  "year": 2023,
  "make": "Land Rover",
  "model": "Range Rover",
  "trim": "Autobiography P530 Amethyst Grey Purple SV MSRP $172,025+ Multimedia",
  "ext": "Amethyst Grey-Purple Ultra Metallic Gloss",
  "price": 99500,
  "status": "Available",
  "flags": [],
  "days": 222,
  "ageLabel": "222d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13052",
  "thumb": null,
  "stock": "22150",
  "year": 2015,
  "make": "Ford",
  "model": "F-350 Super Duty",
  "trim": "Platinum",
  "ext": "White Platinum Metallic Tri-Coat",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 310,
  "ageLabel": "310d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13082",
  "thumb": "8a3ec882-13082_main_t.jpg",
  "stock": "22164",
  "year": 2012,
  "make": "Fisker",
  "model": "Karma EcoSport",
  "trim": "Hybrid Sedan Only 14K Miles Stunning Color Combo Original MSRP $107K+",
  "ext": "Gray",
  "price": 29500,
  "status": "Available",
  "flags": [],
  "days": 303,
  "ageLabel": "303d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13103",
  "thumb": "3e96adee-13103_main_t.jpg",
  "stock": "22182",
  "year": 2003,
  "make": "Porsche",
  "model": "911 Carrera Turbo",
  "trim": "ROOCK Upgrades ONLY 10k Miles Collector Quality Example RARE",
  "ext": "Basalt Black Metallic",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 299,
  "ageLabel": "299d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13140",
  "thumb": "ca81b87c-13140_main_t.jpg",
  "stock": "22215",
  "year": 1967,
  "make": "Ford",
  "model": "Mustang Shelby GT500E",
  "trim": "Eleanor Tribute Unique Performance 427 V8 TREMEC TKO 5-speed",
  "ext": "Yellow",
  "price": 299500,
  "status": "Available",
  "flags": [],
  "days": 282,
  "ageLabel": "282d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13158",
  "thumb": "e8cb5cae-13158_main_t.jpg",
  "stock": "22227",
  "year": 2011,
  "make": "Kenworth",
  "model": "T270",
  "trim": "Service Truck with Crane",
  "ext": "White",
  "price": 89800,
  "status": "Available",
  "flags": [],
  "days": 279,
  "ageLabel": "279d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13167",
  "thumb": "d8b53d72-13167_main_t.jpg",
  "stock": "22231",
  "year": 2022,
  "make": "Ford",
  "model": "F-250 Super Duty",
  "trim": "Lariat SuperCab 6.7L Power Stroke Chrome Pkg Adaptive Steering UTT Camera",
  "ext": "Carbonized Gray",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set"
  ],
  "days": 274,
  "ageLabel": "274d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13174",
  "thumb": null,
  "stock": "22239",
  "year": 2015,
  "make": "McLaren",
  "model": "P1",
  "trim": "",
  "ext": "Titanium Silver",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Sale pending"
  ],
  "days": 271,
  "ageLabel": "271d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13184",
  "thumb": "ec45777c-13184_main_t.jpg",
  "stock": "22245",
  "year": 2019,
  "make": "Porsche",
  "model": "911 Turbo S",
  "trim": "Cabriolet 15k Miles Front Axle Lifter PCCBS Sport Classic Wheels LOADED",
  "ext": "White",
  "price": 182500,
  "status": "Available",
  "flags": [],
  "days": 267,
  "ageLabel": "267d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13202",
  "thumb": null,
  "stock": "22259",
  "year": 1971,
  "make": "Nissan",
  "model": "Skyline GT-R",
  "trim": "",
  "ext": "Silver",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 264,
  "ageLabel": "264d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13208",
  "thumb": null,
  "stock": "22265",
  "year": 1997,
  "make": "Lamborghini",
  "model": "Diablo VT",
  "trim": "Roadster AWD Blu Chiaro 5-Speed Gated Transmission AMAZING CONDITION",
  "ext": "Blu Chiaro",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 261,
  "ageLabel": "261d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13221",
  "thumb": null,
  "stock": "22270",
  "year": 1952,
  "make": "Cunningham",
  "model": "C-4R",
  "trim": "",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 254,
  "ageLabel": "254d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "11869",
  "thumb": "26d0ecdc-11869_main_t.jpg",
  "stock": "22277",
  "year": 2024,
  "make": "Porsche",
  "model": "911 Targa 4 GTS",
  "trim": "Premium Pkg Ice Gray/Bordeaux Red Front End Lifter ANRKY Wheels LOADED",
  "ext": "Ice Grey Metallic",
  "price": 226500,
  "status": "Available",
  "flags": [],
  "days": 257,
  "ageLabel": "257d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13746",
  "thumb": "4d14a564-13746_main_t.jpg",
  "stock": "22282B",
  "year": 2023,
  "make": "Mercedes-Benz",
  "model": "AMG G63",
  "trim": "4x4 Squared! Satin PPF Carbon Pieces Red Interior Roof Rack",
  "ext": "White",
  "price": 275500,
  "status": "Available",
  "flags": [],
  "days": 71,
  "ageLabel": "71d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "13003",
  "thumb": "75170df0-13003_main_t.jpg",
  "stock": "22286C",
  "year": 2022,
  "make": "Aston Martin",
  "model": "DBX",
  "trim": "Black & Dark Chrome Jewelry Packs Touchpad Sport Exhaust Hot Combo",
  "ext": "Silver",
  "price": 97500,
  "status": "Available",
  "flags": [],
  "days": 64,
  "ageLabel": "64d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "13430",
  "thumb": null,
  "stock": "22293",
  "year": 2006,
  "make": "Porsche",
  "model": "Carrera GT",
  "trim": "",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 182,
  "ageLabel": "182d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13259",
  "thumb": null,
  "stock": "22312",
  "year": 1994,
  "make": "Porsche",
  "model": "911",
  "trim": "Turbo",
  "ext": "Black",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 240,
  "ageLabel": "240d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13272",
  "thumb": "6110a03c-13272_main_t.jpg",
  "stock": "22322",
  "year": 2013,
  "make": "Ford",
  "model": "Super Duty F-450 DRW",
  "trim": "",
  "ext": "White",
  "price": 31800,
  "status": "Available",
  "flags": [],
  "days": 233,
  "ageLabel": "233d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13297",
  "thumb": "d6bd1636-13297_main_t.jpg",
  "stock": "22336",
  "year": 1965,
  "make": "Chevrolet",
  "model": "Corvette",
  "trim": "Convertible LS3 540HP 6.2 Restomod OVER $500k+ Build Best of the Best",
  "ext": "Sky Blue",
  "price": 339500,
  "status": "Available",
  "flags": [],
  "days": 225,
  "ageLabel": "225d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13355",
  "thumb": "17000630-13355_main_t.jpg",
  "stock": "22339A",
  "year": 2021,
  "make": "Ford",
  "model": "F150",
  "trim": "Lariat SuperCrew Shelby Pick Up Truck 775HP Whipple Supercharged",
  "ext": "Oxford White",
  "price": 95500,
  "status": "Available",
  "flags": [],
  "days": 202,
  "ageLabel": "202d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13229",
  "thumb": "4a064b64-13229_main_t.jpg",
  "stock": "22344",
  "year": 2023,
  "make": "Audi",
  "model": "SQ5",
  "trim": "3.0T Quattro Premium Plus Navigation Pkg Upgraded Leather Interior Loaded",
  "ext": "Daytona Gray Pearl Effect",
  "price": 35500,
  "status": "Available",
  "flags": [],
  "days": 252,
  "ageLabel": "252d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13233",
  "thumb": "3c9e86b2-13233_main_t.jpg",
  "stock": "22347",
  "year": 2022,
  "make": "Audi",
  "model": "Q8",
  "trim": "Quattro Prestige 55 TFSI B&O Surround Sound Convenience Pkg HUD Loaded",
  "ext": "Mythos Black Metallic",
  "price": 44500,
  "status": "Available",
  "flags": [],
  "days": 252,
  "ageLabel": "252d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "11129",
  "thumb": "b39debe2-11129_main_t.jpg",
  "stock": "22355",
  "year": 2020,
  "make": "Bobcat",
  "model": "S64 Skidloader",
  "trim": "",
  "ext": "White",
  "price": 45800,
  "status": "Available",
  "flags": [],
  "days": 1077,
  "ageLabel": "3y",
  "ageBand": "red",
  "lock": null
 },
 {
  "id": "13312",
  "thumb": "c17fceae-13312_main_t.jpg",
  "stock": "22356",
  "year": 2022,
  "make": "Chevrolet",
  "model": "Silverado 5500 HD",
  "trim": "",
  "ext": "White",
  "price": 49800,
  "status": "Available",
  "flags": [],
  "days": 222,
  "ageLabel": "222d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13314",
  "thumb": "5a06ddaa-13314_main_t.jpg",
  "stock": "22358",
  "year": 2016,
  "make": "International",
  "model": "Terrastar",
  "trim": "Bucket Truck",
  "ext": "White",
  "price": 45800,
  "status": "Available",
  "flags": [],
  "days": 222,
  "ageLabel": "222d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13329",
  "thumb": "1385eb62-13329_main_t.jpg",
  "stock": "22370",
  "year": 2018,
  "make": "Isuzu",
  "model": "NRR",
  "trim": "",
  "ext": "White",
  "price": 58800,
  "status": "Available",
  "flags": [],
  "days": 216,
  "ageLabel": "216d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13330",
  "thumb": "a1539036-13330_main_t.jpg",
  "stock": "22371",
  "year": 2019,
  "make": "Ford",
  "model": "Super Duty F-450 DRW",
  "trim": "XL",
  "ext": "White",
  "price": 49800,
  "status": "Available",
  "flags": [],
  "days": 216,
  "ageLabel": "216d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13333",
  "thumb": null,
  "stock": "22375",
  "year": 1997,
  "make": "Porsche",
  "model": "993 911 Turbo",
  "trim": "",
  "ext": "White",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 215,
  "ageLabel": "215d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13334",
  "thumb": null,
  "stock": "22376",
  "year": 1951,
  "make": "Cadillac",
  "model": "Series 2",
  "trim": "",
  "ext": "Red",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set"
  ],
  "days": 215,
  "ageLabel": "215d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13345",
  "thumb": "5ad29dee-13345_main_t.jpg",
  "stock": "22386",
  "year": 2016,
  "make": "Kenworth",
  "model": "T270",
  "trim": "Service Truck W/ Crane",
  "ext": "White",
  "price": 99800,
  "status": "Available",
  "flags": [],
  "days": 208,
  "ageLabel": "208d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13360",
  "thumb": null,
  "stock": "22396",
  "year": 2006,
  "make": "Porsche",
  "model": "Carrera GT",
  "trim": "",
  "ext": "PTS MoonBeam Metallic",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 201,
  "ageLabel": "201d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "12041",
  "thumb": "66d1403a-12041_main_t.jpg",
  "stock": "22414",
  "year": 1990,
  "make": "Land Rover",
  "model": "Defender 110",
  "trim": "SUV Built by Historic Motoring Solutions 3.5L V8 LT85 5-Speed Manual",
  "ext": "Gray",
  "price": 88500,
  "status": "Available",
  "flags": [
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 195,
  "ageLabel": "195d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13384",
  "thumb": null,
  "stock": "22420",
  "year": 2006,
  "make": "Ford",
  "model": "GT",
  "trim": "",
  "ext": "Heritage Blue Clearcoat",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set"
  ],
  "days": 194,
  "ageLabel": "194d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "11590",
  "thumb": null,
  "stock": "22422",
  "year": 2015,
  "make": "Porsche",
  "model": "918 Spyder",
  "trim": "Paint to Sample Acid Green 3255 Miles Perfect",
  "ext": "PTS Acid Green",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 191,
  "ageLabel": "191d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "10697",
  "thumb": "c95e76e8-10697_main_t.jpg",
  "stock": "22449A",
  "year": 2021,
  "make": "Lamborghini",
  "model": "Aventador",
  "trim": "LP770-4 SVJ Roadster! RARE Blu Nila Electric Seats Carbon Fiber",
  "ext": "Blu Nila Glittered",
  "price": null,
  "status": "Available",
  "flags": [
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 113,
  "ageLabel": "113d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13934",
  "thumb": "8b5f6e22-13934_main_t.jpg",
  "stock": "22488C",
  "year": 1990,
  "make": "Ford",
  "model": "Mustang",
  "trim": "GT 5.0 Hatchback Vortech Supercharged Tremec 5-Speed Incredible Build",
  "ext": "Black",
  "price": 49800,
  "status": "Available",
  "flags": [],
  "days": 20,
  "ageLabel": "20d",
  "ageBand": "green",
  "lock": null
 },
 {
  "id": "13389",
  "thumb": null,
  "stock": "22496",
  "year": 2016,
  "make": "Dodge",
  "model": "Viper GTC ACR",
  "trim": "Only 6K Miles",
  "ext": "Stryker Purple Tri-Coat Pearl",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)"
  ],
  "days": 163,
  "ageLabel": "163d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13568",
  "thumb": "caf744e8-13568_main_t.jpg",
  "stock": "22503A",
  "year": 2021,
  "make": "McLaren",
  "model": "765LT",
  "trim": "Coupe MSO Paris Blue! MSO Black Pack! MSO Stitching! Velos Wheels!",
  "ext": "Blue",
  "price": 739500,
  "status": "Available",
  "flags": [],
  "days": 125,
  "ageLabel": "125d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13479",
  "thumb": null,
  "stock": "22509",
  "year": 2005,
  "make": "Ferrari",
  "model": "575 Superamerica",
  "trim": "",
  "ext": "Red",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 155,
  "ageLabel": "155d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13483",
  "thumb": "7c80cff8-13483_main_t.jpg",
  "stock": "22513",
  "year": 2022,
  "make": "Rolls-Royce",
  "model": "Black Badge Cullinan",
  "trim": "Only 6600 Miles MSRP $440,550+ Mandarin Interior Mansory Widebody",
  "ext": "Black Diamond",
  "price": 659500,
  "status": "Available",
  "flags": [],
  "days": 153,
  "ageLabel": "153d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13819",
  "thumb": null,
  "stock": "22524A",
  "year": 2011,
  "make": "Porsche",
  "model": "911 Carrera S",
  "trim": "Cabriolet 6-Speed Manual Bose Sound System Navigation Heated Seats LOADED",
  "ext": "Black",
  "price": 72500,
  "status": "Available",
  "flags": [
   "No photos uploaded"
  ],
  "days": 50,
  "ageLabel": "50d",
  "ageBand": "slate",
  "lock": null
 },
 {
  "id": "13500",
  "thumb": null,
  "stock": "22526",
  "year": 2026,
  "make": "AGROTK",
  "model": "SDA140T",
  "trim": "Mini Compact Track Loader",
  "ext": "Red",
  "price": 6500,
  "status": "Available",
  "flags": [
   "No photos uploaded"
  ],
  "days": 147,
  "ageLabel": "147d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13501",
  "thumb": "cc0e1eea-13501_main_t.jpg",
  "stock": "22528",
  "year": 2026,
  "make": "SDLANCH",
  "model": "SSL60",
  "trim": "Mini Compact Track Loader",
  "ext": "Yellow",
  "price": 6000,
  "status": "Available",
  "flags": [],
  "days": 147,
  "ageLabel": "147d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13502",
  "thumb": "9851a668-13502_main_t.jpg",
  "stock": "22529",
  "year": 2026,
  "make": "SDLANCH",
  "model": "SSL60",
  "trim": "Mini Compact Track Loader",
  "ext": "Yellow",
  "price": 6000,
  "status": "Available",
  "flags": [],
  "days": 147,
  "ageLabel": "147d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13503",
  "thumb": "64952de6-13503_main_t.jpg",
  "stock": "22530",
  "year": 2026,
  "make": "AGROTK",
  "model": "YSRT14",
  "trim": "Mini Compact Track Loader",
  "ext": "Red",
  "price": 6500,
  "status": "Available",
  "flags": [],
  "days": 147,
  "ageLabel": "147d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13504",
  "thumb": "30d8b564-13504_main_t.jpg",
  "stock": "22531",
  "year": 2026,
  "make": "AGROTK",
  "model": "KKTA27",
  "trim": "Mini Compact Track Loader",
  "ext": "Yellow",
  "price": 14500,
  "status": "Available",
  "flags": [],
  "days": 147,
  "ageLabel": "147d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13358",
  "thumb": "7bca9caa-13358_main_t.jpg",
  "stock": "22536",
  "year": 2021,
  "make": "Koenigsegg",
  "model": "Regera",
  "trim": "Ghost Package 1 of JUST 80 EVER Produced Bespoke Spec Carbon Everywhere",
  "ext": "White/Blue Carbon Fiber",
  "price": 2899500,
  "status": "Available",
  "flags": [],
  "days": 201,
  "ageLabel": "201d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13509",
  "thumb": null,
  "stock": "22537",
  "year": 1989,
  "make": "Porsche",
  "model": "911 Speedster",
  "trim": "",
  "ext": "Gray",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set",
   "Hidden on site (Do Not Display)",
   "Excluded from outbound feeds (nofeedout)",
   "Sale pending"
  ],
  "days": 145,
  "ageLabel": "145d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13569",
  "thumb": null,
  "stock": "22540A",
  "year": 1993,
  "make": "Ford",
  "model": "Mustang SVT Cobra",
  "trim": "",
  "ext": "Bright Red",
  "price": null,
  "status": "Available",
  "flags": [
   "No photos uploaded",
   "No price set"
  ],
  "days": 125,
  "ageLabel": "125d",
  "ageBand": "amber",
  "lock": null
 },
 {
  "id": "13519",
  "thumb": "ea57c31c-13519_main_t.jpg",
  "stock": "22541",
  "year": 2025,
  "make": "Aston Martin",
  "model": "DBX",
  "trim": "707MSRP $280k+ FACTORY WARRANTY Inspire Sport Interior Forged Wheels LOADED",
  "ext": "China Grey",
  "price": 209500,
  "status": "Available",
  "flags": [],
  "days": 141,
  "ageLabel": "141d",
  "ageBand": "amber",
  "lock": null
 }
];
